[package]
name = "lintdiff-stats"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
description = "Statistics collection and aggregation for lintdiff."
publish = false
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
lintdiff-types.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
