[package]
name = "lintdiff-range-merge"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
description = "Line number to range merging utilities for lintdiff."
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
serde = { workspace = true, optional = true, features = ["derive"] }

[features]
default = []
serde = ["dep:serde"]

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
