[package]
name = "lintdiff-code-url"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Source code URL generation for lintdiff"
publish = false

[dependencies]
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
