[package]
name = "lintdiff-render-markdown"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
description = "Markdown rendering of findings for lintdiff."
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
lintdiff-types.workspace = true
lintdiff-stats.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
