[package]
name = "lintdiff-code-policy"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
thiserror.workspace = true
lintdiff-glob = { path = "../lintdiff-glob" }

[dependencies.serde]
workspace = true
optional = true

[dev-dependencies]
lintdiff-glob = { path = "../lintdiff-glob" }
proptest.workspace = true

[lints]
workspace = true
