[package]
name = "lintdiff-app-io"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
description = "IO + config helpers for lintdiff adapters."
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
lintdiff-ingest-core = { path = "../lintdiff-ingest-core" }
lintdiff-types = { path = "../lintdiff-types" }
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true
